.apex/src/objects/Order__c.object
<CustomObject>
    <description>Order__c - new custom object 
Name - String
AccountId - Lookup to Account object
TotalProductCount - Number
TotalPrice - Number</description>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>AccountId - Lookup to Account object</description>
        <label>AccountId</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Name - String</description>
        <label>Name</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <label>TotalPrice</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalProductCount__c</fullName>
        <label>TotalProductCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderItem__c.object
<CustomObject>
    <description>OrderItem__c - new custom object</description>
    <fields>
        <fullName>OrderId__c</fullName>
        <description>OrderId - Master-Detail to Order</description>
        <label>OrderId</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>OrderItems</relationshipLabel>
        <relationshipName>OrderItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <description>Price - Number</description>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProductId__c</fullName>
        <description>ProductId - Master-Detail to Product</description>
        <label>ProductId</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>OrderItems</relationshipLabel>
        <relationshipName>OrderItems</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>OrderItem</label>
    <nameField>
        <label>OrderItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrderItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Name - String</description>
        <label>Name</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OrderItemTriggerTest.cls
@isTest
private class OrderItemTriggerTest {
	@isTest
	static void testAfterInsert() {
		// Create a test Product record
		Product__c testProduct = new Product__c(Name__c = 'Test Product', Description__c = 'Test Description', Price__c = 50);
		insert testProduct;

		// Create a test Order record
		Order__c testOrder = new Order__c(Name__c = 'Test Order', AccountId__c = null, TotalProductCount__c = 5, TotalPrice__c = 10);
		insert testOrder;

		// Create a list of test OrderItems with required fields
		List<OrderItem__c> orderItemsToInsert = new List<OrderItem__c>{
				new OrderItem__c(OrderId__c = testOrder.Id, ProductId__c = testProduct.Id, Quantity__c = 1),
				new OrderItem__c(OrderId__c = testOrder.Id, ProductId__c = testProduct.Id, Quantity__c = 2),
				new OrderItem__c(OrderId__c = testOrder.Id, ProductId__c = testProduct.Id, Quantity__c = 3)
				};

		Test.startTest();
		// Insert the test OrderItems
		insert orderItemsToInsert;
		Test.stopTest();

		// Since this is a simple test, we don't need to add any specific assertions.
		// It's sufficient to reach this point without encountering any exceptions or errors.
		System.assert(true);
	}
}