.apex/src/objects/Order__c.object
<CustomObject>
    <description>Order__c - new custom object 
Name - String
AccountId - Lookup to Account object
TotalProductCount - Number
TotalPrice - Number</description>
    <fields>
        <fullName>Name__c</fullName>
        <description>Name - String</description>
        <label>Name</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <label>TotalPrice</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalProductCount__c</fullName>
        <label>TotalProductCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderItem__c.object
<CustomObject>
    <description>OrderItem__c - new custom object</description>
    <fields>
        <fullName>OrderId__c</fullName>
        <description>OrderId - Master-Detail to Order</description>
        <label>OrderId</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>OrderItems</relationshipLabel>
        <relationshipName>OrderItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <description>Price - Number</description>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProductId__c</fullName>
        <description>ProductId - Master-Detail to Product</description>
        <label>ProductId</label>
        <referenceTo>Product__c</referenceTo>
        <relationshipLabel>OrderItems</relationshipLabel>
        <relationshipName>OrderItems</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>OrderItem</label>
    <nameField>
        <label>OrderItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrderItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

.apex/src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Name__c</fullName>
        <description>Name - String</description>
        <label>Name</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.apex/src/classes/OrderController.cls
public with sharing class OrderController {
	@AuraEnabled
	public static Id checkoutCart(List<Id> productIds) {
		List<OrderItem__c> orderItems = new List<OrderItem__c>();
		Decimal totalPrice = 0;
		Integer totalProductCount = 0;

		// Fetch selected products
		List<Product__c> selectedProducts = [SELECT Id, Name__c, Price__c FROM Product__c WHERE Id IN :productIds];

		// Calculate total price and total product count
		for (Product__c product : selectedProducts) {
			OrderItem__c orderItem = new OrderItem__c(
					ProductId__c = product.Id,
					Quantity__c = 1, // Assuming each product has a quantity of 1 for now
					Price__c = product.Price__c
			);
			orderItems.add(orderItem);
			totalPrice += product.Price__c;
			totalProductCount++;
		}

		// Create Order record
		Order__c newOrder = new Order__c(
				Name__c = 'New Order', // Set a relevant name for the order
				TotalProductCount__c = totalProductCount,
				TotalPrice__c = totalPrice
		);
		insert newOrder;

		// Set the created Order Id for the Order Items
		for (OrderItem__c orderItem : orderItems) {
			orderItem.OrderId__c = newOrder.Id;
		}
		insert orderItems;

		// Return the created Order Id
		return newOrder.Id;
	}
}