.apex/src/objects/Order__c.object
<CustomObject>
    <description>Order__c - new custom object 
Name - String
AccountId - Lookup to Account object
TotalProductCount - Number
TotalPrice - Number</description>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <label>TotalPrice</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalProductCount__c</fullName>
        <label>TotalProductCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Order</label>
    <nameField>
        <label>Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OrderItem__c.object
<CustomObject>
    <description>OrderItem__c - new custom object</description>
    <fields>
        <fullName>OrderId__c</fullName>
        <description>OrderId - Master-Detail to Order</description>
        <label>OrderId</label>
        <referenceTo>Order__c</referenceTo>
        <relationshipLabel>OrderItems</relationshipLabel>
        <relationshipName>OrderItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <description>Price - Number</description>
        <label>Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>OrderItem</label>
    <nameField>
        <label>OrderItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>OrderItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/OrderTriggerHandler.cls
public class OrderTriggerHandler {
	public static void calculateOrderTotals(Set<Id> orderIds) {
		List<Order__c> ordersToUpdate = new List<Order__c>();

		// Query the Order and related OrderItem records
		List<Order__c> ordersWithItems = [SELECT Id, (SELECT Id, Quantity__c, Price__c FROM OrderItems__r) FROM Order__c WHERE Id IN :orderIds];

		// Calculate totals for each Order
		for (Order__c order : ordersWithItems) {
			Integer totalProductCount = 0;
			Decimal totalPrice = 0;

			for (OrderItem__c orderItem : order.OrderItems__r) {
				totalProductCount += (Integer)orderItem.Quantity__c;
				totalPrice += orderItem.Quantity__c * orderItem.Price__c;
			}

			ordersToUpdate.add(new Order__c(Id = order.Id, TotalProductCount__c = totalProductCount, TotalPrice__c = totalPrice));
		}

		// Update the Order records with the calculated totals
		update ordersToUpdate;
	}
}