src/objects/Product__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Family__c</fullName>
        <label>Family</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Catty</fullName>
                </value>
                <value>
                    <fullName>Flat</fullName>
                </value>
                <value>
                    <fullName>House</fullName>
                </value>
                <value>
                    <fullName>Mansion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <description>Image - Url - link to image</description>
        <label>Image</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <description>Name - String</description>
        <label>Name</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2-rooms</fullName>
                </value>
                <value>
                    <fullName>3-rooms</fullName>
                </value>
                <value>
                    <fullName>4-rooms</fullName>
                </value>
                <value>
                    <fullName>5-rooms</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ProductController.cls
public with sharing class ProductController {
	@AuraEnabled
	// Method to perform product search based on Name and Description fields
	public static List<Product__c> searchProducts(String searchText) {
		try {
			// Perform SOQL query to search for products based on Name and Description fields
			// Replace "Product__c" with the actual API name of your custom object for products
			String searchQuery = 'SELECT Name__c, Description__c FROM Product__c WHERE Name__c LIKE :searchText OR Description__c LIKE :searchText';
			List<Product__c> searchResults = Database.query(searchQuery);

			return searchResults;
		} catch (Exception ex) {
			// Handle any exceptions and errors here
			// You can log the error, display a custom error message, or take other actions as needed
			System.debug('Error performing search: ' + ex.getMessage());
			return new List<Product__c>(); // Return an empty list in case of any error
		}
	}
	@AuraEnabled(cacheable=true)
	public static List<Product__c> getProducts() {
		return [SELECT Name__c, Description__c, Type__c, Family__c, Image__c, Price__c FROM Product__c];
	}

	@AuraEnabled
	public static List<Product__c> getFilters(String selectedType, String selectedFamily) {
		String soqlQuery = 'SELECT Name__c, Description__c, Type__c, Family__c, Image__c, Price__c FROM Product__c';
		if (!String.isEmpty(selectedType) && !String.isEmpty(selectedFamily)) {
			soqlQuery += ' WHERE Type__c = :selectedType AND Family__c = :selectedFamily';
		} else if (!String.isEmpty(selectedType)) {
			soqlQuery += ' WHERE Type__c = :selectedType';
		} else if (!String.isEmpty(selectedFamily)) {
			soqlQuery += ' WHERE Family__c = :selectedFamily';
		}
		return Database.query(soqlQuery);
	}

}